urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^wx/$', 'weixin.views.home', name='home'),
    # url(r'^syaweb/', include('syaweb.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^vote/', 'vote.views.vote', name='vote'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

account/models.py
from django.db import models

# Create your models here.

vote/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
import logging,datetime
from uuid import uuid4


DEPARTMENTS = (
	('1',u'eBusiness'),	
	('2',u'PMO'),
	('3',u'HR'),
	('4',u'Infra'),
	('5',u'Finance'),
	('6',u'BI'),
	('7',u'C&BI'),
	('8',u'Transportation'),
	('9',u'DBA'),
)

class Show(models.Model):
	uid = models.CharField(max_length=50,unique=True,verbose_name='UUID',default=uuid4().hex)
	name = models.CharField(max_length=100,verbose_name='Name')
	year = models.CharField(max_length=4,verbose_name='Year')
	department = models.CharField(max_length=1,verbose_name='department',choices=DEPARTMENTS)

	class Meta:
		verbose_name = u'节目show'
		verbose_name_plural = u'节目show'

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			self.uid = uuid4().hex
		return super(Show, self).save(*args, **kwargs)

	def get_votes_count(self):
		return self.votes_set.filter(show=self).count()
	# get_votes_count.admin_order_field = 
	get_votes_count.short_description = '票数统计'

class Votes(models.Model):
	datetime_voted = models.DateTimeField(auto_now_add=True,verbose_name='投票时间')
	name = models.CharField(max_length=50,blank=True,null=True,verbose_name='姓名')
	department = models.CharField(max_length=2,blank=True,null=True,verbose_name='部门',choices=DEPARTMENTS)
	# email = models.EmailField(max_length=50,blank=True,null=True,verbose_name='电子邮件')
	show = models.ForeignKey(Show,blank=True,null=True,verbose_name='节目名称')

	class Meta:
		verbose_name = u'节目投票'
		verbose_name_plural = u'节目投票'

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			self.datetime_voted = datetime.datetime.today()
		return super(Votes, self).save(*args, **kwargs)		

weixin/models.py
from django.db import models

# Create your models here.

account/views.py
# Create your views here.

vote/views.py
# Create your views here.
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response,redirect,render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from vote.models import *

def vote(request):
	if request.method == 'POST':
		selected = request.POST.getlist('selected')
		name = request.POST.get('name','unkonw')
		department = request.POST.get('department','unkonw')

		countsOfVote = Votes.objects.filter(department=department).filter(name=name).count()
		if countsOfVote > 0:
			# return HttpResponse("Sorry! You have already voted!")
			return render(request, 'vote/result.html',{'response':'<h2>Sorry!</h2><p>You have already voted!</p>'})

		if not len(selected) == 2:
			# return HttpResponse("Sorry! You should selected 2 items! Please <a href='/vote'>back</a>")
			return render(request, 'vote/result.html',{'response':'<h2>Sorry!</h2><p>You should selected 2 items! Please <a class="btn btn-primary btn-lg" role="button" href="/vote">back</a></p>'})

		for item in selected:
			new_vote = Votes()
			new_vote.name = name
			new_vote.department = department
			show_id = item
			show = get_object_or_404(Show, pk=show_id)
			new_vote.show = show
			new_vote.save()			
		# return HttpResponse("Thanks for your voting!")
		return render(request, 'vote/result.html',{'response':'<h2>Congratulations!</h2><p>Thanks for your voting</p>'})
	else:
		shows = Show.objects.all().order_by('-year')
		return render(request,'vote/index.html',{'shows':shows})

weixin/views.py
# Create your views here.
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response,redirect,render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

def home(request):
	return render(request, 'wxindex.html')

templates/base.html
{% load cms_tags sekizai_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="data-spm" content="1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
{% block head_quote %}{% endblock %}
<title>{% placeholder "TITLE" %}{% block title %}{% endblock %}</title>
{% render_block "css" %}
<!--自定义CSS&Javascript代码片段begin-->
{% placeholder "CUSTOM_CSS_JS" %}
{% block custom_css_js %}{% endblock %}
<!--自定义CSS&Javascript代码片段end-->
</head>
<body>
{% placeholder "BASE_CONTENT" %}
{% block base_content %}{% endblock %}
{% render_block "js" %}
</body>
</html>

templates/vote/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Vote</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="http://v3.bootcss.com/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://v3.bootcss.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="http://cdn.bootcss.com/jquery/2.1.3/jquery.js"></script>
    <script type="text/javascript">
      function checkValue() {
        if (null == $("#name").val() || "" == $("#name").val()) {
          alert("Your name is required!");
          $("#name").focus();
          return false;
        }

        if ("0" == $("#department").val()) {
          alert("Your department is required!");
          $("#department").focus();
          return false;
        }
        var len = $("input:checkbox:checked").length; 
        if (len == 2) {
          return true;
        } else {
          alert("You should selected 2 items!");
          return false;
        }

        return true;
      }
    </script>
  </head>

  <body>

    <div class="container">
      <!--
      <div class="header">
        <ul class="nav nav-pills pull-right" role="tablist">
          <li role="presentation" class="active"><a href="#">Home</a></li>
          <li role="presentation"><a href="#">About</a></li>
          <li role="presentation"><a href="#">Contact</a></li>
        </ul>
        <h3 class="text-muted">Project name</h3>
      </div>
      -->

      <div class="jumbotron">
      <p>some description ...</p>
      </div>

      <div class="row marketing">
        <form name="voteform" method="POST">{% csrf_token %}
        <div class="col-lg-12">        
        <table class="table table-bordered table-hover table-condensed">
        <thead>
        <tr><th>Show</th><th>Department</th><th>Year</th></tr>
        </thead>
          {% for show in shows %}
          <tr><td>
          <div class="checkbox">
            <label>
              <input name="selected" type="checkbox" value="{{show.pk}}" />
              {{show.name}}
            </label>
          </div>
          </td><td><div class="checkbox"><label>{{show.get_department_display}}</label></div></td><td><div class="checkbox"><label>{{show.year}}</label></div></td></tr>
          {% endfor %}
        </table>
        </div>

        <div class="col-lg-12">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">Your Team</div>
              <select class="form-control" id="department" name="department">
              <option value="0">====Please select====</option>
            <option value="1">eBusiness</option>
            <option value="2">PMO</option>
            <option value="3">HR</option>
            <option value="4">Infra</option>
            <option value="5">Finance</option>              
            <option value="6">BI</option>
            <option value="7">C&BI</option>
            <option value="8">Transportation</option>
            <option value="9">DBA</option>
              </select>
            </div>
          </div>
        </div>

        <div class="col-lg-12">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">Your Name</div>
              <input class="form-control" type="text" id="name" name="name" maxlength="30" placeholder="Enter your name">
            </div>
          </div>
        </div>

        <div class="col-lg-12">
        <p><input class="btn btn-lg btn-success" type="submit" onclick="return checkValue();" value="&nbsp;Vote&nbsp;" /></p>
        </div>
        </form>

<!--       <div class="footer">
        <p>&copy; Company 2014</p>
      </div> -->

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v3.bootcss.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/vote/result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Result</title>

    <!-- Bootstrap core CSS -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="http://v3.bootcss.com/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://v3.bootcss.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="http://cdn.bootcss.com/jquery/2.1.3/jquery.js"></script>
  </head>

  <body>

    <div class="container">
      <div class="jumbotron">

      {{response|safe}}
<!--         <h2>Hello, world!</h2>
        <p>...</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p> -->

      </div>
    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v3.bootcss.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/wxindex.html
<!DOCTYPE HTML>
<HTML lang="ch">
<HEAD>
<META content="IE=11.0000" http-equiv="X-UA-Compatible">
<TITLE>从这里开始</TITLE>     
<META charset="utf-8">     
<META name="apple-touch-fullscreen" content="YES">     
<META name="format-detection" content="telephone=no">     
<META name="apple-mobile-web-app-capable" content="yes">     
<META name="apple-mobile-web-app-status-bar-style" content="black">     
<META http-equiv="Expires" content="-1">     
<META http-equiv="pragram" content="no-cache">     
<LINK href="/static/css/weixin/34653ccf4281c63e1639404852a_p1_mk1.css" rel="stylesheet" type="text/css">     
<LINK href="/static/css/weixin/3d93496103df4f3793597f2b8f8_p1_mk1.css" rel="stylesheet" type="text/css"> 
<LINK href="/static/css/weixin/867f29aed7bf867d97f47c3b8de_p1_mk1.css" rel="stylesheet" type="text/css">   
<SCRIPT src="/static/js/weixin/4abcf40a4a6d6c2abc0c6abe4a5_p1_mk1.js" type="text/javascript"></SCRIPT>
	<!--移动端版本兼容 -->     
	<SCRIPT type="text/javascript">
        var phoneWidth = parseInt(window.screen.width);
        var phoneScale = phoneWidth / 640;

        var ua = navigator.userAgent;
        if (/Android (d+.d+)/.test(ua)) {
            var version = parseFloat(RegExp.$1);
            // andriod 2.3
            if (version > 2.3) {
                document.write('<meta name="viewport" content="width=640, minimum-scale = ' + phoneScale + ', maximum-scale = ' + phoneScale + ', target-densitydpi=device-dpi">');
                // andriod 2.3以上
            } else {
                document.write('<meta name="viewport" content="width=640, target-densitydpi=device-dpi">');
            }
            // 其他系统
        } else {
            document.write('<meta name="viewport" content="width=640, user-scalable=no, target-densitydpi=device-dpi">');
        }
    </SCRIPT>
	<STYLE>
	.u-buy .buybtn {
		left: -450px;
		top:-880px;
		width: 168px;
		height: 53px;
		line-height: 53px;
		vertical-align: middle;
		display: inline-block;
		position: absolute;
		
	}
<!-- ↑↑↑上面改“团购报名”图片链接-->
	</STYLE>
     <!--移动端版本兼容 end --> 
<META name="GENERATOR" content="MSHTML 11.00.9600.17207"></HEAD> 
<BODY class="s-bg-ddd"><!--模版加载提示-->    
 <SECTION 
class="u-audio f-hide" data-src="http://www1.qjmy.cn/media/filer_public/a0/b0/a0b09a8e-cd15-4ae2-b203-97bfbf2a116d/start_from_here.mp3">
<P class="btn_audio" id="coffee_flow">		<STRONG 
class="txt_audio z-hide">关闭</STRONG>             <SPAN class="css_sprite01 audio_open"></SPAN> 
   </P></SECTION>   
<!-- 这里改报名链接 -->  

 <SECTION class="u-alert"><IMG style="display: none;" 
src="/static/img/weixin/a6dbd9b32b2ce52a9bc1b38db00_p1_mk1.gif">         
<DIV class="alert-loading z-move">
<DIV class="cycleWrap"><SPAN class="cycle cycle-1"></SPAN>                 <SPAN 
class="cycle cycle-2"></SPAN>                 <SPAN 
class="cycle cycle-3"></SPAN>                 <SPAN 
class="cycle cycle-4"></SPAN>             </DIV>
<DIV class="lineWrap"><SPAN class="line line-1"></SPAN>                 <SPAN 
class="line line-2"></SPAN>                 <SPAN class="line line-3"></SPAN>    
    </DIV></DIV></SECTION><!--模版加载提示 end--> 
         

   
<!-- 这里改报名链接 -->  
<SECTION class="u-buy"><A href="#">

<P class="buybtn"></P></A>     </SECTION><!-- 声音控件 end-->     <!-- 箭头指示引导 -->    
 <SECTION class="u-arrow f-hide">
<P class="css_sprite01"></P></SECTION>     <!-- 箭头指示引导 end-->     <!-- page页面内容 -->
<SECTION class="p-ct">
  <!-- 旋转正面 -->
  <!-- 旋转正面 end-->
  <!-- 旋转反面 -->
  <div class="translate-back f-hide">
    <!-- 封页 1-->
    <!-- 封面 建议尺寸640*960 -->
    <div class="m-page m-bigTxt" data-statics="info_list" data-page-type="bigTxt">
      <div class="translate-front" id="j-mengban">
        <div class="mengban-warn"></div>
      </div>
      <div class="page-con j-txtWrap lazy-img" data-src="/static/img/weixin/7ba9cf912d83b801cbbc8c4e3f3_p1_mk1.jpg "></div>
    </div>
    <!-- 封面 -->
    <!-- 第1张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="translate-front" id="j-mengban">
        <div class="mengban-warn"></div>
      </div>
      <div class="page-con j-txtWrap lazy-img" data-src="
/static/img/weixin/360943afec9db8dd0f08d4581c8_p1_mk1.jpg"></div>
    </div>
    <!-- 第1张图 end-->
    <!-- 第2张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="page-con j-txtWrap lazy-img" data-src="/static/img/weixin/94a1a67c66a8ffe408d07ea7543_p1_mk1.jpg"></div>
    </div>
    <!-- 第2张图 end-->
    <!-- 第3张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="page-con j-txtWrap lazy-img" data-src="

/static/img/weixin/8b3d495c196299c220ba4d26b8c_p1_mk1.jpg "></div>
    </div>
    <!-- 第3张图 end-->
    <!-- 第4张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="page-con j-txtWrap lazy-img" data-src="

/static/img/weixin/1ed662c4060a4ba190f7c63d40c_p1_mk1.jpg "></div>
    </div>
    <!-- 第4张图 end-->
     <!-- 第5张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="page-con j-txtWrap lazy-img" data-src="

/static/img/weixin/51ae88841461986d33894e36f01_p1_mk1.jpg "></div>
</div>
    <!-- 第5张图 end-->
     <!-- 第6张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="page-con j-txtWrap lazy-img" data-src="

/static/img/weixin/c2cb1f3447d0ea3b2965a88f453_p1_mk1.jpg "></div>
</div>
    <!-- 第6张图 end-->
     <!-- 第7张图 -->
    <div class="m-page m-bigTxt f-hide" data-statics="info_list" data-page-type="bigTxt">
      <div class="page-con j-txtWrap lazy-img" data-src="

/static/img/weixin/789861d9bd6d1fdc0fe25cbe1fd_p1_mk1.jpg ">
    </div>
    <!-- 第7张图 end-->
     <!-- 第8张图 -->
  </div>
  <!-- 旋转反面 end-->
</SECTION>
<!-- 正文介绍 end-->
<!-- lightapp入口 end-->
<!--pageLoading-->

<SECTION class="u-pageLoading"><IMG 
alt="loading" src="/static/img/weixin/load.gif">     </SECTION>     <!--pageLoading end--> 
	<!-- 资源传递-->
    
	<!-- 模版ID--><input id="activity_id" type="hidden" value='3464' />	
	<!-- 微信分享信息--><!-- 微信分享信息--><input id="r-wx-title" type="hidden" value=
从这里开始
	<!-- 微信分享信息--><input id="r-wx-img"   type="hidden" value="/static/img/weixin/a614b7ba00feecf6d4c9404415e_p1_mk1.jpg" />
	<!-- 微信分享信息--><!-- 资源传递 end--> 
  
    <!--脚本加载-->     
<input id="r-wx-con"   type="hidden" value=从这里开始
	<!-- 资源传递 end--> 
  
    <!--脚本加载-->     
<SCRIPT src="/static/js/weixin/c26cb4bad9e8c1d0325da2dd64e_p1_mk1.js" type="text/javascript" charset="utf-8"></SCRIPT>
     
<SCRIPT src="/static/js/weixin/b683e3d75fa0a93a903f5d2aad5_p1_mk1.js" type="text/javascript" charset="utf-8"></SCRIPT>
     
<SCRIPT src="/static/js/weixin/23ee4166621709d82cab01428ed_p1_mk1.js" type="text/javascript" charset="utf-8"></SCRIPT>
     
<SCRIPT src="/static/js/weixin/2510106d2770a0996f2c598f5f0_p1_mk1.js" type="text/javascript" charset="utf-8"></SCRIPT>
     
<SCRIPT src="/static/js/weixin/72089758880566827d1274e8fb3_p1_mk1.js" type="text/javascript" charset="utf-8"></SCRIPT>
     
<SCRIPT src="/static/js/weixin/30f75651de9e903deb8c76d3b2b_p1_mk1.js" type="text/javascript" charset="utf-8" defer＝'defer'=""></SCRIPT>
<!--脚本加载 end--> <script type="text/javascript" src="/static/js/weixin/helper.loader.js"></script><!-- START OF SmartSource Data Collector TAG -->
<SCRIPT SRC="/static/js/weixin/fangchan_5s7f_tag.js" TYPE="text/javascript"></SCRIPT>
<!-- END OF SmartSource Data Collector TAG -->
<script type="text/javascript" src="/static/js/weixin/helper.loader.js"></script><!-- START OF SmartSource Data Collector TAG -->
<SCRIPT SRC="/static/js/weixin/fangchan_5s7f_tag.js" TYPE="text/javascript"></SCRIPT>
<!-- END OF SmartSource Data Collector TAG -->
<script type="text/javascript" src="/static/js/weixin/helper.loader.js"></script><!-- START OF SmartSource Data Collector TAG -->
<SCRIPT SRC="/static/js/weixin/fangchan_5s7f_tag.js" TYPE="text/javascript"></SCRIPT>
<!-- END OF SmartSource Data Collector TAG -->
<script type="text/javascript" src="/static/js/weixin/helper.loader.js"></script><!-- START OF SmartSource Data Collector TAG -->
<SCRIPT SRC="/static/js/weixin/fangchan_5s7f_tag.js" TYPE="text/javascript"></SCRIPT>
<!-- END OF SmartSource Data Collector TAG -->
<script type="text/javascript" src="/static/js/weixin/helper.loader.js"></script><!-- START OF SmartSource Data Collector TAG -->
<SCRIPT SRC="/static/js/weixin/fangchan_5s7f_tag.js" TYPE="text/javascript"></SCRIPT>
<!-- END OF SmartSource Data Collector TAG -->
<script type="text/javascript" src="/static/js/weixin/helper.loader2.js"></script><!-- START OF SmartSource Data Collector TAG -->
<SCRIPT SRC="/static/js/weixin/fangchan_5s7f_tag.js" TYPE="text/javascript"></SCRIPT>
<!-- END OF SmartSource Data Collector TAG -->
</body></HTML>